spring.application.name=SpringHill
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_hill_db
spring.datasource.username=yourusername
spring.datasource.password=yourpassword
spring.jpa.hibernate.ddl-auto=update

